=== sgibson91/warmup-sets-calculator/sets-definition-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "set_num": {
          "type": "number"
        },
        "min_weight_multiplier": {
          "type": "number"
        },
        "max_weight_multiplier": {
          "type": "number"
        },
        "reps": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "set_num",
        "min_weight_multiplier",
        "max_weight_multiplier",
        "reps",
        "description"
      ]
    }
  }

=== sgibson91/warmup-sets-calculator/sets-definition.json
[
    {
        "set_num": 1,
        "min_weight_multiplier": 0,
        "max_weight_multiplier": 0,
        "reps": "5",
        "description": "Start with an empty bar"
    },
    {
        "set_num": 2,
        "min_weight_multiplier": 0.4,
        "max_weight_multiplier": 0.5,
        "reps": "5",
        "description": "40-50% of your first working set"
    },
    {
        "set_num": 3,
        "min_weight_multiplier": 0.6,
        "max_weight_multiplier": 0.65,
        "reps": "3-5",
        "description": "60-65% of your first working set"
    },
    {
        "set_num": 4,
        "min_weight_multiplier": 0.7,
        "max_weight_multiplier": 0.8,
        "reps": "3",
        "description": "70-80% of your first working set"
    },
    {
        "set_num": 5,
        "min_weight_multiplier": 0.85,
        "max_weight_multiplier": 0.9,
        "reps": "1-3",
        "description": "85-90% of your first working set"
    },
    {
        "set_num": 6,
        "min_weight_multiplier": 0.9,
        "max_weight_multiplier": 0.95,
        "reps": "1-3",
        "description": "90-95% of your first working set"
    }
]
